### ISSUE TITLE
Separate iTunes Reporter Configs

### ISSUE THREAD

**Issue by michellevballen** [fleet-data/fleet#11]
Currently, iTunes Reporter combines three different files into one table (examples listed below).

Subscriber_86807785_20170816.txt.gz
Subscription_Event_86807785_20170816.txt.gz
Subscription_86807785_20170816.txt.gz

Would prefer to have three separate configs since the data in each file is unique. Thanks

**Comment by brettgriffin** [comment]
@jre247: I was under the impression that each of three files were 1/3 of the same set of data. Since these are three completely different reports, we should make these three separate result sets that can be requested. We will need to decide the values for each of these properties for the each of three reports:

`reportCategory`
`reportType`
`reportSubType`

The following fields will returned from each report:

**Subscription:**
App Name
App Apple ID
Subscription Name
Subscription Apple ID
Subscription Group ID
Subscription Duration
Customer Price
Customer Currency
Developer Proceeds
Proceeds Currency
Preserved Pricing
Proceeds Reason
Client
Device
State
Country
Active Subscriptions
Active Free Trials
Marketing Opt-Ins

**Subscriber:**
Event Date
App Name
App Apple ID
Subscription Name
Subscription Apple ID
Subscription Group ID
Subscription Duration
Trial Duration
Marketing Opt-In Duration
Customer Price
Customer Currency
Developer Proceeds
Proceeds Currency
Preserved Pricing
Proceeds Reason
Client
Device
Country
Subscriber ID
Subscriber ID
Reset
Refund
Purchase Date
Units

**Subscription Event:**
Event Date
Event
App Name
App Apple ID
Subscription Name
Subscription Apple ID
Subscription Group ID
Subscription Duration
Trial	
Trial Duration
Marketing Opt-In
Marketing Opt-In Duration
Preserved Pricing
Proceeds Reason
Consecutive Paid Periods
Original Start Date	Client
Device
State
Country
Previous Subscription
Name
Previous Subscription Apple ID
Days Before Canceling
Cancellation Reason
Days Canceled
Quantity

**Comment by jre247** [comment]
Fleet 0.0.74 has a fix for this.

**Comment by brettgriffin** [comment]
Closing this issue as we have moved it to fleet-data/fleet-source-itunes-reporter#13
